[phases.setup]
nixPkgs = [
  "mesa",
  "libglvnd",
  "glib",
  "xorg.libXext",
  "xorg.libSM",
  "xorg.libXrender"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT}"