[phases.setup]
nixPkgs = [
  "stdenv.cc.cc.lib",
  "zlib",
  "mesa",
  "libglvnd",
  "glib",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libSM",
  "xorg.libXrender",
  "xorg.libICE"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT}"